/* eslint-disable @typescript-eslint/naming-convention */
export enum ProvinceEnum {
  'Baghdad' = 'Baghdad',
  'Basra' = 'Basra',
  'Maysan' = 'Maysan',
  'DhiQar' = 'DhiQar',
  'Diyala' = 'Diyala',
  'Dohuk' = 'Dohuk',
  'Erbil' = 'Erbil',
  'Karbala' = 'Karbala',
  'Kirkuk' = 'Kirkuk',
  'Muthanna' = 'Muthanna',
  'Najaf' = 'Najaf',
  'Nineveh' = 'Nineveh',
  'Saladin' = 'Saladin',
  'Sulaymaniyah' = 'Sulaymaniyah',
  'Wasit' = 'Wasit',
  'Al-Anbar' = 'Al-Anbar',
  'Babil' = 'Babil',
}
