enum Role {
  SUPERADMIN = 'SUPERADMIN',
  ADMIN = 'ADMIN',
  COUSTOMER = 'COUSTOMER',
  SHOPADMIN = 'SHOPADMIN',
  DELIVERYBOY = 'DELIVERYBOY',
  DELIVERYBOYMANGER = 'DELIVERYBOYMANGER',
  DELIVERYBOYADMIN = 'DELIVERYBOYADMIN',
  SHOPCASHER = 'SHOPCASHER',
  SHOPMANGER = 'SHOPMANGER',
  COUSTOMERSERVICE = 'COUSTOMERSERVICE',
  COUSTOMERSERVICEMANGER = 'COUSTOMERSERVICEMANGER',
  PRODUCTEDITOR = 'PRODUCTEDITOR',
  ACOUNTINT = 'ACOUNTINT',
}
export default Role;
